import type { Product } from './types'

const U = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=600&h=800&fit=crop&auto=format&q=80`

const IMG = {
  peony:  [U('1558618666-fcd25c85cd64'), U('1561181286-d3fee7d55364')],
  rose:   [U('1548142813-c348350df52b'), U('1455582916367-25f75bfc6710'), U('1518895949257-7621c3c786d7')],
  tulip:  [U('1462275646964-a0e3386b89fa'), U('1520763185298-1b434c919102')],
  daisy:  [U('1508193638397-1c4234db14d8'), U('1444021465936-c6ca81d39b84')],
  mixed:  [U('1530092376999-2431865aa8df'), U('1526047932273-341f2a7631f9'), U('1502977249166-824b3a8a4d6d')],
  white:  [U('1508610048659-a06b669e3321'), U('1599733594230-6b823276abcc')],
  exotic: [U('1606041011872-596597976b25'), U('1459411552884-841db9b3cc2a')],
  garden: [U('1490914327627-9fe8d52f4d90'), U('1444021465936-c6ca81d39b84')],
}

export const MOCK_PRODUCTS: Product[] = [
  // ── Розы (букеты) ─────────────────────────────────────────────────────────
  {
    id: '1', slug: 'krasnye-rozy-21',
    name: 'Классические красные розы',
    composition: '21 роза сорта Фридом, гипсофила, декоративная зелень',
    images: [IMG.rose[0], IMG.rose[1]],
    price: 2200, oldPrice: 2800, discount: 20,
    rating: 4.9, reviewCount: 87,
    occasions: ['birthday', 'wedding'], flowerTypes: ['rose'], colors: ['red'],
    isHit: true, inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1400 },
      { id: 'm', label: 'M', price: 2200, oldPrice: 2800 },
      { id: 'l', label: 'L', price: 3200 },
    ],
  },
  {
    id: '2', slug: 'roza-devid-ostin',
    name: 'Роза Дэвид Остин',
    composition: '15 роз Дэвид Остин, эвкалипт, питтоспорум',
    images: [IMG.rose[2], IMG.rose[0]],
    price: 4500,
    rating: 5.0, reviewCount: 42,
    occasions: ['wedding', 'birthday'], flowerTypes: ['rose'], colors: ['pink', 'white'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 2900 },
      { id: 'm', label: 'M', price: 4500 },
      { id: 'l', label: 'L', price: 6200 },
    ],
  },
  {
    id: '3', slug: 'rozy-miks-rozovye',
    name: 'Розовый микс роз',
    composition: '25 роз разных оттенков розового, лента, упаковка',
    images: [IMG.rose[1], IMG.rose[2]],
    price: 1800,
    rating: 4.7, reviewCount: 63,
    occasions: ['birthday', 'mom'], flowerTypes: ['rose'], colors: ['pink'],
    isNew: true, inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1100 },
      { id: 'm', label: 'M', price: 1800 },
      { id: 'l', label: 'L', price: 2600 },
    ],
  },
  {
    id: '4', slug: 'belye-rozy-mono',
    name: 'Монобукет белых роз',
    composition: '19 белых роз Аваланш, флористическая бумага',
    images: [IMG.rose[2], IMG.rose[1]],
    price: 1900,
    rating: 4.8, reviewCount: 34,
    occasions: ['wedding', 'sorry'], flowerTypes: ['rose'], colors: ['white'],
    isNew: true, inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1200 },
      { id: 'm', label: 'M', price: 1900 },
      { id: 'l', label: 'L', price: 2800 },
    ],
  },
  // ── Розы (штучные) ────────────────────────────────────────────────────────
  {
    id: '5', slug: 'alye-rozy-11',
    name: '11 алых роз',
    composition: 'Розы Red Naomi — поштучный выбор количества',
    images: [IMG.rose[0], IMG.rose[2]],
    price: 120, oldPrice: 150, discount: 20,
    rating: 4.6, reviewCount: 119,
    occasions: ['birthday', 'sorry', 'mom'], flowerTypes: ['rose'], colors: ['red'],
    isHit: true, inStock: true, deliverToday: true,
    kind: 'single', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    stemPrice: 120, stemOptions: [1, 5, 11, 25, 51, 101],
    sizes: [
      { id: 'm', label: 'M', price: 1320 },
    ],
  },
  {
    id: '6', slug: 'rozy-gipsofila',
    name: 'Розы с гипсофилой',
    composition: '15 роз Эквадор, облако гипсофилы, рускус',
    images: [IMG.rose[1], IMG.rose[0]],
    price: 2800,
    rating: 4.8, reviewCount: 55,
    occasions: ['wedding', 'birthday'], flowerTypes: ['rose'], colors: ['red', 'pink'],
    inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1800 },
      { id: 'm', label: 'M', price: 2800 },
      { id: 'l', label: 'L', price: 4000 },
    ],
  },

  // ── Пионы ─────────────────────────────────────────────────────────────────
  {
    id: '7', slug: 'piony-nezhno-rozovye',
    name: 'Нежные розовые пионы',
    composition: '15 пионов сорта Сара Бернар, листья эвкалипта',
    images: [IMG.peony[0], IMG.peony[1]],
    price: 3200, oldPrice: 4000, discount: 20,
    rating: 4.9, reviewCount: 78,
    occasions: ['birthday', 'wedding', 'mom'], flowerTypes: ['peony'], colors: ['pink'],
    isHit: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 2100 },
      { id: 'm', label: 'M', price: 3200, oldPrice: 4000 },
      { id: 'l', label: 'L', price: 4600 },
    ],
  },
  {
    id: '8', slug: 'belye-piony',
    name: 'Белоснежные пионы',
    composition: '11 белых пионов Duchesse de Nemours, зелень смилакс',
    images: [IMG.peony[1], IMG.peony[0]],
    price: 2900,
    rating: 5.0, reviewCount: 31,
    occasions: ['wedding', 'birthday'], flowerTypes: ['peony'], colors: ['white'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1900 },
      { id: 'm', label: 'M', price: 2900 },
      { id: 'l', label: 'L', price: 4100 },
    ],
  },
  {
    id: '9', slug: 'piony-korobka',
    name: 'Пионы в шляпной коробке',
    composition: '20 пионов, мох, сухоцветы, шляпная коробка',
    images: [IMG.peony[0], IMG.peony[1]],
    price: 4100,
    rating: 4.9, reviewCount: 22,
    occasions: ['birthday', 'wedding'], flowerTypes: ['peony'], colors: ['pink', 'white'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 2700 },
      { id: 'm', label: 'M', price: 4100 },
      { id: 'l', label: 'L', price: 5800 },
    ],
  },
  // ── Пионы (штучные) ───────────────────────────────────────────────────────
  {
    id: '10', slug: 'piony-poshtuchno',
    name: 'Пионы поштучно',
    composition: 'Пионы с эвкалиптом — выбор количества стеблей',
    images: [IMG.peony[1], IMG.peony[0]],
    price: 280,
    rating: 4.7, reviewCount: 44,
    occasions: ['mom', 'birthday', 'sorry'], flowerTypes: ['peony'], colors: ['pink'],
    inStock: true, deliverToday: false,
    kind: 'single', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    stemPrice: 280, stemOptions: [1, 5, 11, 25, 51],
    sizes: [
      { id: 'm', label: 'M', price: 3080 },
    ],
  },

  // ── Тюльпаны ──────────────────────────────────────────────────────────────
  {
    id: '11', slug: 'tyulpany-51',
    name: 'Тюльпаны 51 шт',
    composition: '51 тюльпан разных цветов, упаковка крафт',
    images: [IMG.tulip[0], IMG.tulip[1]],
    price: 2100, oldPrice: 2600, discount: 20,
    rating: 4.8, reviewCount: 142,
    occasions: ['birthday', 'mom', 'other'], flowerTypes: ['tulip'], colors: ['purple', 'pink', 'yellow'],
    isHit: true, inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1000 },
      { id: 'm', label: 'M', price: 2100, oldPrice: 2600 },
      { id: 'l', label: 'L', price: 3500 },
    ],
  },
  {
    id: '12', slug: 'tyulpany-poshtuchno',
    name: 'Тюльпаны поштучно',
    composition: 'Тюльпаны Purple Prince — выбор количества стеблей',
    images: [IMG.tulip[1], IMG.tulip[0]],
    price: 60,
    rating: 4.7, reviewCount: 58,
    occasions: ['birthday', 'mom'], flowerTypes: ['tulip'], colors: ['purple'],
    inStock: true, deliverToday: true,
    kind: 'single', freshness: 'live', packagingOptions: ['no_basket'],
    stemPrice: 60, stemOptions: [5, 11, 25, 51, 101],
    sizes: [
      { id: 'm', label: 'M', price: 660 },
    ],
  },
  {
    id: '13', slug: 'zhyoltye-tyulpany-25',
    name: 'Жёлтые тюльпаны',
    composition: '25 тюльпанов Strong Gold, бумажная упаковка',
    images: [IMG.tulip[0], IMG.tulip[1]],
    price: 900,
    rating: 4.6, reviewCount: 73,
    occasions: ['birthday', 'other'], flowerTypes: ['tulip'], colors: ['yellow'],
    inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 550 },
      { id: 'm', label: 'M', price: 900 },
      { id: 'l', label: 'L', price: 1350 },
    ],
  },
  {
    id: '14', slug: 'tyulpany-boks',
    name: 'Тюльпаны в боксе',
    composition: '35 тюльпанов, флористический мох, деревянный ящик',
    images: [IMG.tulip[1], IMG.tulip[0]],
    price: 3000,
    rating: 4.9, reviewCount: 19,
    occasions: ['birthday', 'wedding'], flowerTypes: ['tulip'], colors: ['purple', 'pink'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket'],
    sizes: [
      { id: 's', label: 'S', price: 1900 },
      { id: 'm', label: 'M', price: 3000 },
      { id: 'l', label: 'L', price: 4300 },
    ],
  },

  // ── Весенний/луговой микс ─────────────────────────────────────────────────
  {
    id: '15', slug: 'vesenniy-miks',
    name: 'Весенний микс',
    composition: 'Тюльпаны, нарциссы, фрезия, мимоза — 7 видов',
    images: [IMG.mixed[0], IMG.mixed[2]],
    price: 1900, oldPrice: 2400, discount: 20,
    rating: 4.8, reviewCount: 96,
    occasions: ['birthday', 'mom', 'other'], flowerTypes: ['mixed'], colors: ['yellow', 'pink', 'white'],
    isHit: true, inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1200 },
      { id: 'm', label: 'M', price: 1900, oldPrice: 2400 },
      { id: 'l', label: 'L', price: 2800 },
    ],
  },
  {
    id: '16', slug: 'lugovye-tsvety',
    name: 'Луговые цветы',
    composition: 'Ромашки, васильки, полевые тюльпаны, сухоцветы, колоски',
    images: [IMG.mixed[1], IMG.mixed[0]],
    price: 1100,
    rating: 4.6, reviewCount: 47,
    occasions: ['other', 'birthday', 'mom'], flowerTypes: ['mixed'], colors: ['white', 'yellow', 'purple'],
    inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 700 },
      { id: 'm', label: 'M', price: 1100 },
      { id: 'l', label: 'L', price: 1600 },
    ],
  },
  // ── Сухоцветы ─────────────────────────────────────────────────────────────
  {
    id: '17', slug: 'polevoy-buket-sukhoy',
    name: 'Полевой букет сухоцветов',
    composition: 'Гипсофила, хлопок, эвкалипт, лаванда, сухие травы',
    images: [IMG.mixed[2], IMG.mixed[1]],
    price: 1300,
    rating: 4.7, reviewCount: 61,
    occasions: ['birthday', 'other', 'sorry'], flowerTypes: ['mixed'], colors: ['white', 'green'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'dried', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 850 },
      { id: 'm', label: 'M', price: 1300 },
      { id: 'l', label: 'L', price: 1900 },
    ],
  },
  {
    id: '18', slug: 'sadovyy-miks',
    name: 'Садовый микс',
    composition: 'Розы, пионы, гортензия, лизиантус — премиум состав',
    images: [IMG.mixed[0], IMG.mixed[1]],
    price: 2500,
    rating: 4.8, reviewCount: 38,
    occasions: ['birthday', 'wedding'], flowerTypes: ['mixed'], colors: ['pink', 'white', 'purple'],
    inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1600 },
      { id: 'm', label: 'M', price: 2500 },
      { id: 'l', label: 'L', price: 3600 },
    ],
  },

  // ── Белые / хризантемы ────────────────────────────────────────────────────
  {
    id: '19', slug: 'belye-romashki',
    name: 'Садовые ромашки',
    composition: '50 ромашек, флористическая лента, крафт-упаковка',
    images: [IMG.daisy[0], IMG.daisy[1]],
    price: 850,
    rating: 4.5, reviewCount: 82,
    occasions: ['birthday', 'other', 'mom'], flowerTypes: ['mixed'], colors: ['white', 'yellow'],
    inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 550 },
      { id: 'm', label: 'M', price: 850 },
      { id: 'l', label: 'L', price: 1250 },
    ],
  },
  {
    id: '20', slug: 'belye-khrizantemy',
    name: 'Белые хризантемы',
    composition: '25 хризантем Bacardi, декоративная зелень, рафия',
    images: [IMG.daisy[1], IMG.daisy[0]],
    price: 1100, oldPrice: 1400, discount: 20,
    rating: 4.7, reviewCount: 53,
    occasions: ['birthday', 'other', 'funeral'], flowerTypes: ['mixed'], colors: ['white'],
    inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 700 },
      { id: 'm', label: 'M', price: 1100, oldPrice: 1400 },
      { id: 'l', label: 'L', price: 1600 },
    ],
  },
  // ── Сухоцветы (монобуке) ──────────────────────────────────────────────────
  {
    id: '21', slug: 'sukhye-tsvety-pampas',
    name: 'Пампасная трава и сухоцветы',
    composition: 'Пампасная трава, хлопок, лагурус, гелихризум, лаванда',
    images: [IMG.white[0], IMG.white[1]],
    price: 2300,
    rating: 4.9, reviewCount: 27,
    occasions: ['wedding', 'birthday', 'sorry'], flowerTypes: ['mixed'], colors: ['white'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'dried', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1500 },
      { id: 'm', label: 'M', price: 2300 },
      { id: 'l', label: 'L', price: 3300 },
    ],
  },
  {
    id: '22', slug: 'klassicheskiy-belyy',
    name: 'Классический белый',
    composition: '21 эустома, гипсофила, рускус — элегантный моно',
    images: [IMG.white[1], IMG.white[0]],
    price: 1700,
    rating: 4.8, reviewCount: 41,
    occasions: ['wedding', 'sorry', 'other'], flowerTypes: ['mixed'], colors: ['white'],
    inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1100 },
      { id: 'm', label: 'M', price: 1700 },
      { id: 'l', label: 'L', price: 2400 },
    ],
  },

  // ── Экзотика ──────────────────────────────────────────────────────────────
  {
    id: '23', slug: 'ekzoticheskiy-buket',
    name: 'Экзотический букет',
    composition: 'Протея, стрелиция, антуриум, тропические листья',
    images: [IMG.exotic[0], IMG.exotic[1]],
    price: 3800,
    rating: 4.9, reviewCount: 16,
    occasions: ['birthday', 'other'], flowerTypes: ['orchid'], colors: ['pink', 'purple', 'orange'],
    isNew: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 2500 },
      { id: 'm', label: 'M', price: 3800 },
      { id: 'l', label: 'L', price: 5400 },
    ],
  },
  {
    id: '24', slug: 'sadovye-gortenzii',
    name: 'Садовые гортензии',
    composition: '5 гортензий разных цветов, флористическая зелень',
    images: [IMG.garden[0], IMG.garden[1]],
    price: 3100, oldPrice: 3900, discount: 20,
    rating: 4.8, reviewCount: 29,
    occasions: ['birthday', 'wedding', 'mom'], flowerTypes: ['orchid'], colors: ['pink', 'blue', 'white'],
    isHit: true, inStock: true, deliverToday: false,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['basket', 'no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 2000 },
      { id: 'm', label: 'M', price: 3100, oldPrice: 3900 },
      { id: 'l', label: 'L', price: 4400 },
    ],
  },

  // ── Траурные ──────────────────────────────────────────────────────────────
  {
    id: '25', slug: 'traurnyy-buket',
    name: 'Траурный букет',
    composition: '15 белых хризантем, белые лилии, зелень — сдержанная элегантность',
    images: [IMG.white[0], IMG.daisy[0]],
    price: 1600,
    rating: 4.8, reviewCount: 12,
    occasions: ['funeral'], flowerTypes: ['mixed'], colors: ['white'],
    inStock: true, deliverToday: true,
    kind: 'bouquet', freshness: 'live', packagingOptions: ['no_basket'],
    sizes: [
      { id: 's', label: 'S', price: 1000 },
      { id: 'm', label: 'M', price: 1600 },
      { id: 'l', label: 'L', price: 2300 },
    ],
  },
]
